RUN_STRINGS = (
    "Now you see me, now you don't."
    "ε=ε=ε=ε=┌(;￣▽￣)┘",
    "Get back here!",
    "REEEEEEEEEEEEEEEEEE!!!!!!!",
    "Look out for the wall!",
    "Don't leave me alone with them!!",
    "You've got company!",
    "Chotto matte!",
    "Yare yare daze",
    "*Naruto run activated*",
    "*Nezuko run activated*",
    "Hey take responsibilty for what you just did!",
    "May the odds be ever in your favour.",
    "Run everyone, they just dropped a bomb 💣💣",
    "And they disappeared forever, never to be seen again.",
    "Legend has it, they're still running.",
    "Hasta la vista, baby.",
    "Ah, what a waste. I liked that one.",
    "As The Doctor would say... RUN!",
)

GIFS = [
    'CgACAgQAAx0CSVUvGgAC7KpfWxMrgGyQs-GUUJgt-TSO8cOIDgACaAgAAlZD0VHT3Zynpr5nGxsE',
    'CgACAgUAAx0CU_rCTAABAjdgX1s4NVaeCls6YaH3p43vgdCRwQIAAqsAA4P_MFUYQhyoR-kgpRsE',
    'CgACAgUAAx0CU_rCTAABAjdSX1s3fq5iEJ64YeQLKI8cD7CSuSEAAlUBAAJu09hW5iqWB0hTPD4bBA'
]

SLAP_SAITAMA_TEMPLATES = (
    "Slap me one more time and I'll mute you.",
    "Stop slapping me. REEEEEEEEEEEEEE.",
    [
        "I am muting you for a minute.",  # normal reply
        "Stop slapping me just because I can't mute you. REEEEEEEEEE.",  # reply to admin
        "tmute",  # command
        "Shut up!",
        "Silence!"
    ])

SLAP_TEMPLATES = (
    "{user2} was killed by magic.",
    "{user2} starved without pats.",
    "{user2} was knocked into the void by {user1}.",
    "{user2} fainted.",
    "{user2} is out of usable Pokemon! {user2} whited out!.",
    "{user2} is out of usable Pokemon! {user2} blacked out!.",
    "{user2} got rekt.",
    "{user2}'s melon was split by {user1}.",
    "{user2} was sliced and diced by {user1}.",
    "{user2} played hot-potato with a grenade.",
    "{user2} was knifed by {user1}.",
    "{user2} ate a grenade.",
    "{user2} is what's for dinner!",
    "{user2} was terminated by {user1}.",
    "{user1} spammed {user2}'s email.",
    "{user1} RSA-encrypted {user2} and deleted the private key.",
    "{user1} put {user2} in the friendzone.",
    "{user1} slaps {user2} with a DMCA takedown request!",
    "{user2} got a house call from Doctor {user1}.",
    "{user1} beheaded {user2}.",
    "{user2} got stoned...by an angry mob.",
    "{user1} sued the pants off {user2}.",
    "{user2} was one-hit KO'd by {user1}.",
    "{user1} sent {user2} down the memory hole.",
    "{user2} was a mistake. - '{user1}' ",
    "{user2} was made redundant.",
    "{user1} {hits} {user2} with a bat!.",
    "{user1} {hits} {user2} with a Taijutsu Kick!.",
    "{user1} {hits} {user2} with X-Gloves!.",
    "{user1} {hits} {user2} with a Jet Punch!.",
    "{user1} {hits} {user2} with a Jet Pistol!.",
    "{user1} {hits} {user2} with a United States of Smash!.",
    "{user1} {hits} {user2} with a Detroit Smash!.",
    "{user1} {hits} {user2} with a Texas Smash!.",
    "{user1} {hits} {user2} with a California Smash!.",
    "{user1} {hits} {user2} with a New Hampshire Smash!.",
    "{user1} {hits} {user2} with a Missouri Smash!.",
    "{user1} {hits} {user2} with a Carolina Smash!.",
    "{user1} {hits} {user2} with a King Kong Gun!.",
    "{user1} {hits} {user2} with a baseball bat - metal one.!.",
    "*Serious punches {user2}*.",
    "*Normal punches {user2}*.",
    "*Consecutive Normal punches {user2}*.",
    "*Two Handed Consecutive Normal Punches {user2}*.",
    "*Ignores {user2} to let them die of embarassment*.",
    "*points at {user2}* What's with this sassy... lost child?.",
    "*Hits {user2} with a Fire Tornado*.",
    "{user1} pokes {user2} in the eye !",
    "{user1} pokes {user2} on the sides!",
    "{user1} pokes {user2}!",
    "{user1} pokes {user2} with a needle!",
    "{user1} pokes {user2} with a pen!",
    "{user1} pokes {user2} with a stun gun!",
    "{user2} is secretly a Furry!",
    "Hey Everybody! {user1} is asking me to be mean!",
    "( ･_･)ﾉ⌒●~* (･.･;) <-{user2}",
    "Take this {user2}\n(ﾉﾟДﾟ)ﾉ ))))●~* ",
    "Here {user2} hold this\n(｀・ω・)つ ●~＊",
    "( ・_・)ノΞ●~*  {user2}\nDieeeee!!.",
    "( ・∀・)ｒ鹵~<≪巛;ﾟДﾟ)ﾉ\n*Bug sprays {user2}*.",
    "( ﾟДﾟ)ﾉ占~<巛巛巛.\n-{user2} You pest!",
    "( う-´)づ︻╦̵̵̿╤── \(˚☐˚”)/ {user2}.",
    "{user1} {hits} {user2} with a {item}.",
    "{user1} {hits} {user2} in the face with a {item}.",
    "{user1} {hits} {user2} around a bit with a {item}.",
    "{user1} {throws} a {item} at {user2}.",
    "{user1} grabs a {item} and {throws} it at {user2}'s face.",
    "{user1} launches a {item} in {user2}'s general direction.",
    "{user1} starts slapping {user2} silly with a {item}.",
    "{user1} pins {user2} down and repeatedly {hits} them with a {item}.",
    "{user1} grabs up a {item} and {hits} {user2} with it.",
    "{user1} ties {user2} to a chair and {throws} a {item} at them.",
    "{user1} gave a friendly push to help {user2} learn to swim in lava.",
    "{user1} bullied {user2}.",
    "Nyaan ate {user2}'s leg. *nomnomnom*",
    "{user1} {throws} a master ball at {user2}, resistance is futile.",
    "{user1} hits {user2} with an action beam...bbbbbb (ง・ω・)ง ====*",
    "{user1} ara ara's {user2}.",
    "{user1} ora ora's {user2}.",
    "{user1} muda muda's {user2}.",
    "{user2} was turned into a Jojo reference!",
    "{user1} hits {user2} with {item}.",
    "Round 2!..Ready? .. FIGHT!!",
    "WhoPixel will oof {user2} to infinity and beyond.",
    "{user2} ate a bat and discovered a new disease.",
    "{user1} folded {user2} into a paper plane",
    "{user1} served {user2} some bat soup.",
    "{user2} was sent to his home, the planet of the apes.",
    "{user1} kicked {user2} out of a moving train.",
    "{user2} just killed John Wick’s dog.",
    "{user1} performed an Avada Kedavra spell on {user2}.",
    "{user1} subjected {user2} to a fiery furnace.",
    "Sakura Haruno just got more useful than {user2}",
    "{user1} unplugged {user2}'s life support.",
    "{user1} subscribed {user2}' to 5 years of bad internet.",
    "You know what’s worse than Dad jokes? {user2}!",
    "{user1} took all of {user2}'s cookies.",
    "{user2} wa mou.......Shindeiru! - {user1}.",
    "{user2} lost his race piece!",  #No game no life reference
    "Shut up {user2}, you are just {user2}.",  #No game no life reference
    "{user1} hits {user2} with Aka si anse!",  #No game no life reference
    "@NeoTheKitty scratches {user2}",  #Pixels pet cat - @NeoTheKitty 
    "Majin buu ate {user2}",  #Dbz
    "Goblin slayer slays {user2}",  #Goblin Slayer
)

PAT_TEMPLATES = (
    "{user1} pats {user2} on the head.",
    "*gently rubs {user2}'s head*.",
    "*{user1} mofumofus {user2}'s head*",
    "*{user1} messes up {user2}'s head*",
    "*{user1} intensly rubs {user2}'s head*",
    "*{user2}'s waifu pats their head*",
    "*{user2}'s got free headpats*",
    "No pats for {user2}!",
    "Oh no! We are all out of pats.",
    "This is a designated no pat zone!",
    "No pats for {user2}!",
    "{user1} spoils {user2} with headpats!",
    "{user2} received one free headpat!",
    "{user1} headpats {user2} whilst giving a lap pillow",
    "{user1} aggressively pats {user2}",
    "{user1} gently strokes {user2}'s head",
    "Pat, pat, pat, pat",
    "{user2} could not escape {user1}'s headpats",
    "{user2}.exe has stopped working",
    "{user1} rubs {user2} on the neck",
    "Must... extort... HEADPATS",
    "{user1} headpats {user2}'s head with a pat",
    "{user1} pats {user2} unexpectedly",
    "{user1} pats {user2} with consent, maybe?",
    "Pat pat, {user2} honto kawaii ne!",
    "{user1} headpats {user2} at 420apm",
    "{user1} bellyrubs {user2}",
    "{user1} pats {user2} friendlily",
    "{user2} uses HEADPATS? O KAWAII KOTO",
    "*headpats.gif intensifies for {user2}*",
    "(*´ω´(*｀ω｀)",
    "(ｏ・_・)ノ”(ᴗ_ ᴗ。)",
    "(*￣▽￣)ノ”(- -*)",
    "(っ´ω`)ﾉ(╥ω╥)",
    "( ´Д｀)ﾉ(´･ω･`) ﾅﾃﾞﾅﾃﾞ",
)

PAT_GIFS = (
    "CgACAgQAAx0CVIxhUQABBPBqX6vdaOZAh-oEMkhr-YWiZRaT4d0AAmUCAALTGoxSFYSCjyjQw4ceBA",
    "CgACAgQAAx0CVIxhUQABBPBrX6vda2H3ndz9bItHho7hHPYhgzcAAmACAAL1G4xSe4c88D6r_0QeBA",
    "CgACAgQAAx0CVIxhUQABBPBsX6vdcChswNvhzn9SX2n7dWWdbIMAAi8CAAIThY1S7EzxeOq7lnMeBA",
    "CgACAgQAAx0CVIxhUQABBPBtX6vdctBhMfHafbAXZ0KTKGI3sk4AAkcCAAI68I1SGSVAPZxn8FMeBA",
    "CgACAgQAAx0CVIxhUQABBPBuX6vddzBrAW7RMLOJTPe7L6GbhLUAAnoCAAJ2D9VQ903bbGnfonseBA",
    "CgACAgQAAx0CVIxhUQABBPBvX6vdeSdSOA44JIHATc8yoA9hB9AAAk8CAAIpO_1SjyLzlc6U2jMeBA",
    "CgACAgQAAx0CVIxhUQABBPBwX6vdfSzhkHq4zVSRaehP685OC6kAAh4CAAJPcjxQK0-BFUKPS3keBA",
    "CgACAgQAAx0CVIxhUQABBPBxX6vdfu5iI046FwYQ8-eTX1IUWcwAAhUCAAJ5VtVSMnu7A64nFyoeBA",
    "CgACAgQAAx0CVIxhUQABBPByX6vdf0w3SnsIvD2lE0QaDKv15LMAAiMCAAI3KIxSKBWsoGMyVdMeBA",
    "CgACAgQAAx0CVIxhUQABBPBzX6vdgPZ3xUB5kCUJ5rOCeiVlD9cAAiQCAALHb9RS5D9chc10JU0eBA",
    "CgACAgQAAx0CVIxhUQABBPB0X6vdgeeWISo24Dlbc3x3GHOtlmcAAjICAAJi3v1SKalLvmlnxSYeBA",
    "CgACAgQAAx0CVIxhUQABBPB1X6vdg3MKn9G-V18Ql4rChw6JNecAAjMCAAJ-4oxS042ErKcOHU8eBA",
    "CgACAgQAAx0CVIxhUQABBPB2X6vdhKM-uWFDz7TvebNt7hpfm78AAlwCAAJH8Y1SW3_ZGMhg_UIeBA",
    "CgACAgQAAx0CVIxhUQABBPB3X6vdhr807S_TGtiR7E62DPd1KfsAAiICAAKWSNVSe0DCWq2bgpYeBA",
    "CgACAgUAAx0CVIxhUQABBPB-X6vd0-7kD95VOWaMyGP5V7864p8AAosBAAKlEGFVdjgfsh20ZyceBA")

PAT_STICKERS = (
    "CAACAgQAAxkBAALRWV9Xs4HH0XaXfhZe-jWaZoXfs-IsAAJYAwACdDgSEHYOt4KvL02oGwQ",
    "CAACAgQAAxkBAALRXF9Xs6XmIeDbnoL1wiDky0TdX-CvAAKKAQAC1TMzC9A3CtiT2rqVGwQ")


WYR_STRINGS = (
	"Would you rather 🔴 go into the past and meet your ancestors or 🔵 go into the future and meet your great-great grandchildren?",
	"Would you rather 🔴 have more time or 🔵 more money?",
	"Would you rather 🔴 have a rewind button or 🔵 a pause button on your life?",
	"Would you rather 🔴 be able to talk with the animals or 🔵 speak all foreign languages?",
	"Would you rather 🔴 win the lottery or 🔵 live twice as long?",
	"Would you 🔴 feel worse if no one showed up to your wedding or 🔵 to your funeral?",
	"Would you rather 🔴 be without internet for a week, or 🔵 without your phone?",
	"Would you rather 🔴 meet your Nikola Tesla, or 🔵 the Elbert Einstein?",
	"Would you rather 🔴 the aliens that make first contact be robotic or 🔵 organic?",
	"Would you rather 🔴 lose the ability to read or 🔵 lose the ability to speak?",
)
#🔴🔵

PING_STRING = (
    "PONG!!",
    "I am here!",
)

ITEMS = (
    "cast iron skillet",
    "angry meow",
    "cricket bat",
    "wooden cane",
    "shovel",
    "toaster",
    "book",
    "laptop",
    "rubber chicken",
    "spiked bat",
    "heavy rock",
    "chunk of dirt",
    "ton of bricks",
    "rasengan",
    "spirit bomb",
    "100-Type Guanyin Bodhisattva",
    "rasenshuriken",
    "Murasame",
    "ban",
    "chunchunmaru",
    "Kubikiribōchō",
    "rasengan",
    "spherical flying kat",
)

THROW = (
    "throws",
    "flings",
    "chucks",
    "hurls",
)

HIT = (
    "hits",
    "whacks",
    "slaps",
    "smacks",
    "bashes",
    "pats",
)

EYES = [['⌐■', '■'], [' ͠°', ' °'], ['⇀', '↼'], ['´• ', ' •`'], ['´', '`'],
        ['`', '´'], ['ó', 'ò'], ['ò', 'ó'], ['⸌', '⸍'], ['>',
                                                         '<'], ['Ƹ̵̡', 'Ʒ'],
        ['ᗒ', 'ᗕ'], ['⟃', '⟄'], ['⪧', '⪦'], ['⪦', '⪧'], ['⪩', '⪨'], ['⪨', '⪩'],
        ['⪰', '⪯'], ['⫑', '⫒'], ['⨴', '⨵'], ['⩿', '⪀'], ['⩾', '⩽'], ['⩺', '⩹'],
        ['⩹', '⩺'], ['◥▶', '◀◤'], ['◍', '◎'], ['/͠-', '┐͡-\\'], ['⌣', '⌣”'],
        [' ͡⎚', ' ͡⎚'], ['≋'], ['૦ઁ'], ['  ͯ'], ['  ͌'], ['ළ'], ['◉'], ['☉'],
        ['・'], ['▰'], ['ᵔ'], [' ﾟ'], ['□'], ['☼'], ['*'], ['`'], ['⚆'], ['⊜'],
        ['>'], ['❍'], ['￣'], ['─'], ['✿'], ['•'], ['T'], ['^'], ['ⱺ'], ['@'],
        ['ȍ'], ['  '], ['  '], ['x'], ['-'], ['$'], ['Ȍ'], ['ʘ'], ['Ꝋ'],
        [''], ['⸟'], ['๏'], ['ⴲ'], ['◕'], ['◔'], ['✧'], ['■'], ['♥'], [' ͡°'],
        ['¬'], [' º '], ['⨶'], ['⨱'], ['⏓'], ['⏒'], ['⍜'], ['⍤'], ['ᚖ'], ['ᴗ'],
        ['ಠ'], ['σ'], ['☯']]

MOUTHS = [['v'], ['ᴥ'], ['ᗝ'], ['Ѡ'], ['ᗜ'], ['Ꮂ'], ['ᨓ'], ['ᨎ'],
          ['ヮ'], ['╭͜ʖ╮'], [' ͟ل͜'], [' ͜ʖ'], [' ͟ʖ'], [' ʖ̯'], ['ω'], [' ³'],
          [' ε '], ['﹏'], ['□'], ['ل͜'], ['‿'], ['╭╮'], ['‿‿'], ['▾'], ['‸'],
          ['Д'], ['∀'], ['!'], ['人'], ['.'], ['ロ'], ['_'], ['෴'], ['ѽ'], ['ഌ'],
          ['⏠'], ['⏏'], ['⍊'], ['⍘'], ['ツ'], ['益'], ['╭∩╮'], ['Ĺ̯'], ['◡'],
          [' ͜つ']]

EARS = [
    ['q', 'p'],
    ['ʢ', 'ʡ'],
    ['⸮', '?'],
    ['ʕ', 'ʔ'],
    ['ᖗ', 'ᖘ'],
    ['ᕦ', 'ᕥ'],
    ['ᕦ(', ')ᕥ'],
    ['ᕙ(', ')ᕗ'],
    ['ᘳ', 'ᘰ'],
    ['ᕮ', 'ᕭ'],
    ['ᕳ', 'ᕲ'],
    ['(', ')'],
    ['[', ']'],
    ['¯\\_', '_/¯'],
    ['୧', '୨'],
    ['୨', '୧'],
    ['⤜(', ')⤏'],
    ['☞', '☞'],
    ['ᑫ', 'ᑷ'],
    ['ᑴ', 'ᑷ'],
    ['ヽ(', ')ﾉ'],
    ['\\(', ')/'],
    ['乁(', ')ㄏ'],
    ['└[', ']┘'],
    ['(づ', ')づ'],
    ['(ง', ')ง'],
    ['⎝', '⎠'],
    ['ლ(', 'ლ)'],
    ['ᕕ(', ')ᕗ'],
    ['(∩', ')⊃━☆ﾟ.*'],
]

TOSS = (
    "Heads",
    "Tails",
)

DECIDE = ("Yes.", "No.", "Maybe.")

TABLE = ("(╯°□°）╯彡 ┻━┻", "I ran out of tables, will order more.",
         "Go do some work instead of flippin tables.")

TRUTH_STRINGS = (
   #Truth or Dare Questions
   " What’s the last lie you told?",
   "What was the most embarrassing thing you’ve ever done on a date?",
   "Have you ever accidentally hit something (or someone!) with your car?",
   "Name someone you’ve pretended to like but actually couldn’t stand.",
   "What’s your most bizarre nickname?",
   "What’s been your most physically painful experience?",
   "What bridges are you glad that you burned?",
   "What’s the craziest thing you’ve done on public transportation?",
   "If you met a genie, what would your three wishes be?",
   "If you could write anyone on Earth in for President of the United States, who would it be and why?",
   "What’s the meanest thing you’ve ever said to someone else?",
   "Who was your worst kiss ever?",
   "What’s one thing you’d do if you knew there no consequences?",
   "What’s the craziest thing you’ve done in front of a mirror?",
   "What’s the meanest thing you’ve ever said about someone else?",
   "What’s something you love to do with your friends that you’d never do in front of your partner?",
   "Who are you most jealous of?",
   "What do your favorite pajamas look like?",
   "Have you ever faked sick to get out of a party?",
   "Who’s the oldest person you’ve dated?",
   "How many selfies do you take a day?",
   "Meatloaf says he’d do anything for love, but he won’t do “that.” What’s your “that?”",
   "How many times a week do you wear the same pants?",
   "Would you date your high school crush today?",
   "Where are you ticklish?",
   "Do you believe in any superstitions? If so, which ones?",
   "What’s one movie you’re embarrassed to admit you enjoy?",
   "What’s your most embarrassing grooming habit?",
   "When’s the last time you apologized? What for?",
   "How do you really feel about the Twilight saga?",
   "Where do most of your embarrassing odors come from?",
   "Have you ever considered cheating on a partner?",
   "Have you ever cheated on a partner?",
   "Boxers or briefs?",
   "Have you ever peed in a pool?",
   "What’s the weirdest place you’ve ever grown hair?",
   "If you were guaranteed to never get caught, who on Earth would you murder?",
   "What’s the cheapest gift you’ve ever gotten for someone else?",
   "What app do you waste the most time on?",
   "What’s the weirdest thing you’ve done on a plane?",
   "Have you ever been nude in public?",
   "How many gossip blogs do you read a day?",
   "What is the youngest age partner you’d date?",
   "Have you ever picked your nose in public?",
   "Have you ever lied about your age?",
   "If you had to delete one app from your phone, which one would it be?",
   "What’s your most embarrassing late night purchase?",
   "What’s the longest you’ve gone without showering?",
   "Have you ever used a fake ID?",
   "Who’s your hall pass?",
   "Be honest: Do you have a favorite child?",
   "Which of your family members annoys you the most and why?",
   "What is your greatest fear in a relationship?",
   "What’s your biggest pet peeve about the person to your left?",
   "What’s the most embarrassing text in your phone right now?",
   "Have you ever seen a dead body?",
   "What celebrity do you think is overrated?",
   "Have you ever lied to your boss?",
   "Have you ever stolen something from work?",
   "What’s the longest you’ve gone without brushing your teeth?",
   "What’s your biggest regret in life?",
   "Who would you hate to see naked?",
   "Describe the weirdest thing you’ve ever done while inebriated.",
   "Have you ever regifted a present?",
   "Who will be your choice to become your boyfriend/girlfriend from the group?",
   "If you had a chance to kill someone, who would it be from the group?",
   "Who is the most hated and liked person in your group from your perspective?",
   "Have you ever loved someone, if so, who was it and for how long, if not, how will you show your love to them?",
   "If you were asked to propose someone from your friends on Telegram, who will be your first choice and why?",
   "If you were to hate someone from your friends on Telegram, who will be your first choice and why?",
   "What are your views on the topic of Human Cannibalism?",
   "If you were asked to kill someone in your most horrific way, how will it be?",
)



DARE_STRINGS = (
   "Change your profile pic to some naked character for 3 days.",
   "Do a photograph reveal.",
   "Share your telegram password.",
   "Send 'I Love You' to 20 people in your PM [Private Messaging] list and share screenshots of the task.",
   "Send hentai to 10 people in your PM [Private Messaging list and share screenshots of the task.",
   "Send your phone number to 10 people in the group and share screenshots of the task.",
   "Share your every social media account username.",
   "Send most embarrising photograph.",
   "Send 'I want your nudes' to 10 people in your PM [Private Messaging list and share screenshots of the task.]",
   "Make your phone number public for 3 minutes.",
   "Set your bio as, 'I am gay and I want to sleep with the person reading this right now' for 2 days.",
   "Suggest more dares to @DarkSamuraiBot",
   "Send the pictures of your ex's panties.",
   "Ask for nudes from strangers and share screenshots of the task.",
   "Share screenshot from most recent chat on WhatsApp.",
   "Join/Start Voice Chat and sing a song.",
   "Join/Start Voice Chat and say, 'Ara Ara', in sexy voice",
   "Go to a random group with its Voice Chat ongoing and members speaking. Join the group and shout 'Fuck you all'. [Screen Record the task and send it in group.]",
   "Go to a random group with its Voice Chat ongoing and members speaking. Join the group and seduce a person. [Screen Record the task and send it in group.]",
   "Download a nude pic using google, PM it to a member of random Anime themed Group with caption as, 'These nudes are mine, wanna share yours?'. [Share screenshots of the task.]",
   "Open the top most chat on your PM List and screen record chat for last 3 days and send it in group.",
   "Reveal your instagram password to someone who is online.",
   "Click a photo of yours right now and send it in group.",
   "Set your bio as, 'Free blowjob if you send your nudes.' for 2 days.",
   "Join/Start Voice Chat and say, 'Onii Chan no Hentai', in sexy voice.",
   "Let someone from the players log in to your Telegram account.",
   "Send 10 most recent images from your galary.",
)



TORD_STRINGS = (
   "Change your profile pic to a dog.",
   "Do a photograph reveal.",
   "Share your telegram password.",
   "Send 'I Love You' to 20 people in your PM [Private Messaging] list and share screenshots of the task.",
   "Send hentai to 10 people in your PM [Private Messaging list and share screenshots of the task.",
   "Send your phone number to 10 people in the group and share screenshots of the task.",
   "Share your every social media account username.",
   "Send most embarrising photograph.",
   "Send 'I want your nudes' to 10 people in your PM [Private Messaging list and share screenshots of the task.",
   "Make your phone number public for 3 minutes.",
   "Set your bio as, 'I am gay and I want to sleep with the person reading this right now' for 2 days.",
   "Suggest more dares to @MaiSakurajima7",
   " What’s the last lie you told?",
   "What was the most embarrassing thing you’ve ever done on a date?",
   "Have you ever accidentally hit something (or someone!) with your car?",
   "Name someone you’ve pretended to like but actually couldn’t stand.",
   "What’s your most bizarre nickname?",
   "What’s been your most physically painful experience?",
   "What bridges are you glad that you burned?",
   "What’s the craziest thing you’ve done on public transportation?",
   "If you met a genie, what would your three wishes be?",
   "If you could write anyone on Earth in for President of the United States, who would it be and why?",
   "What’s the meanest thing you’ve ever said to someone else?",
   "Who was your worst kiss ever?",
   "What’s one thing you’d do if you knew there no consequences?",
   "What’s the craziest thing you’ve done in front of a mirror?",
   "What’s the meanest thing you’ve ever said about someone else?",
   "What’s something you love to do with your friends that you’d never do in front of your partner?",
   "Who are you most jealous of?",
   "What do your favorite pajamas look like?",
   "Have you ever faked sick to get out of a party?",
   "Who’s the oldest person you’ve dated?",
   "How many selfies do you take a day?",
   "Meatloaf says he’d do anything for love, but he won’t do “that.” What’s your “that?”",
   "How many times a week do you wear the same pants?",
   "Would you date your high school crush today?",
   "Where are you ticklish?",
   "Do you believe in any superstitions? If so, which ones?",
   "What’s one movie you’re embarrassed to admit you enjoy?",
   "What’s your most embarrassing grooming habit?",
   "When’s the last time you apologized? What for?",
   "How do you really feel about the Twilight saga?",
   "Where do most of your embarrassing odors come from?",
   "Have you ever considered cheating on a partner?",
   "Have you ever cheated on a partner?",
   "Boxers or briefs?",
   "Have you ever peed in a pool?",
   "What’s the weirdest place you’ve ever grown hair?",
   "If you were guaranteed to never get caught, who on Earth would you murder?",
   "What’s the cheapest gift you’ve ever gotten for someone else?",
   "What app do you waste the most time on?",
   "What’s the weirdest thing you’ve done on a plane?",
   "Have you ever been nude in public?",
   "How many gossip blogs do you read a day?",
   "What is the youngest age partner you’d date?",
   "Have you ever picked your nose in public?",
   "Have you ever lied about your age?",
   "If you had to delete one app from your phone, which one would it be?",
   "What’s your most embarrassing late night purchase?",
   "What’s the longest you’ve gone without showering?",
   "Have you ever used a fake ID?",
   "Who’s your hall pass?",
   "Who will be your choice to become your boyfriend/girlfriend from the group?",
   "If you had a chance to kill someone, who would it be from the group?",
   "Who is the most hated and liked person in your group from your perspective?",
   "Have you ever loved someone, if so, who was it and for how long, if not, how will you show your love to them?",
   "If you were asked to propose someone from your friends on Telegram, who will be your first choice and why?",
   "If you were to hate someone from your friends on Telegram, who will be your first choice and why?",
   "What are your views on the topic of Human Cannibalism?",
   "If you were asked to kill someone in your most horrific way, how will it be?",
   "Join/Start Voice Chat and sing a song.",
   "Join/Start Voice Chat and say, 'Ara Ara', in sexy voice",
   "Go to a random group with its Voice Chat ongoing and members speaking. Join the group and shout 'Fuck you all'. [Screen Record the task and send it in group.]",
   "Go to a random group with its Voice Chat ongoing and members speaking. Join the group and seduce a person. [Screen Record the task and send it in group.]",
   "Download a nude pic using google, PM it to a member of random Anime themed Group with caption as, 'These nudes are mine, wanna share yours?'. [Share screenshots of the task.]",
   "Open the top most chat on your PM List and screen record chat for last 3 days and send it in group.",
   "Reveal your instagram password to someone who is online.",
   "Click a photo of yours right now and send it in group.",
   "Set your bio as, 'Free blowjob if you send your nudes.' for 2 days.",
   "Join/Start Voice Chat and say, 'Onii Chan no Hentai', in sexy voice.",
   "Let someone from the players log in to your Telegram account.",
   "Send 10 most recent images from your galary.",
)
